### ISSUE TITLE
Delegate handler not started when using chord.Join

### ISSUE THREAD

**Issue by euforia** [armon/go-chord#4]
When joining a ring i.e. `chord.Join` the delegate handler is not called after the ring is initialized. This causes the node to hang indefinitely after issuing a `ring.Leave()` as the delegate channel is never drained.

This patch https://github.com/euforia/go-chord/commit/708d7dbd822b0f6ce929d9387c2a1f6bd75ce296  seems to fix the the problem but i'm not sure if this is the right approach.

 Am I doing something wrong or missing something?

**Comment by armon** [comment]
@euforia This is pretty close! I think instead you need a call to `ring.schedule()` which will do the same initialization. Apologies for the delay, also took me a while to context switch, haven't looked at this code in a few years!

**Comment by armon** [comment]
If you open a PR, happy to merge it

**Comment by euforia** [comment]
Correct me if I'm wrong but `ring.schedule` also calls `vnode.schedule`.  From my tests `vnode.schedule` doesn't seem to be required when using `Join` rather only when issuing a `Create`, hence the reason for starting the delegate handler directly.

**Comment by armon** [comment]
Fixed by #5. Thanks!
