### ISSUE TITLE
Constantly rising connection count.

### ISSUE THREAD

**Issue by euforia** [armon/go-chord#7]
I am noticing there is a build up of open sockets which are constantly rising.

It looks like it traces back to this [line 158](https://github.com/armon/go-chord/blob/master/net.go#L158).  When [line 156](https://github.com/armon/go-chord/blob/master/net.go#L156) errors, an explicit call to `out.sock.Close()` is needed before proceeding.  I've tested this out and can confirm it fixes the issues.

I would be more than happy to submit a PR if that is ok?  Please let me know.

**Comment by armon** [comment]
@euforia Please feel free to submit a PR! Thanks!
